baseURL = "https://fukugit.github.io/blog/"
languageCode = "ja-JP"
title = "Blog"
theme = "github-style"

[params]
  author = "fukuro"
  description = "This is my blog. "
  github = "fukugit"
  twitter = "kurrow1"
  utterances = "github/github.github.io"
  avatar = "https://avatars1.githubusercontent.com/u/8071941?s=460&v=4"
  url = "https://github.com/fukugit"
